from pathlib import Path
OUT=Path(__file__).parent
adrs=[
('001','Use ElevenLabs as the managed live voice runtime','Accepted','Quantum Parks requires a high-quality AI receptionist but does not need to build carrier, media, STT, TTS, or turn-taking infrastructure.','Use ElevenLabs to receive and conduct live calls and emit provider call data. Quantum Parks integrates by supported APIs, tools, personalization, webhooks, and telephony configuration.','Faster delivery and managed voice quality. Creates provider dependency and requires explicit capability, privacy, and cost governance. A custom media gateway is prohibited as the primary design.'),
('002','Make the Quantum Parks application the exclusive normal-user control plane','Accepted','Normal users should not need the ElevenLabs console for day-to-day work.','Provide agent, prompt, workflow, tool, transfer, voice, knowledge, test, release, monitoring, and reconciliation workflows in the Quantum Parks application.','Requires broader provider API integration and drift detection. Console exceptions are limited to vendor onboarding/billing/API-inaccessible capabilities.'),
('003','Use a local-master and remote-runtime-copy synchronization model','Accepted','Provider objects are required at runtime but must not become the business source of truth.','Store immutable approved local versions and map them to provider object IDs/hashes. Publish through durable workflows and verify by read-back.','Supports audit and rollback. Requires reconciliation, checksums, capability mapping, and drift incidents.'),
('004','Use signed, fast, idempotent post-call ingestion','Accepted','Provider post-call events must not be lost or block on enrichment.','Verify signature/replay, persist raw evidence and inbox record, acknowledge quickly, and process asynchronously.','Supports replay and duplicate safety. Requires restricted raw storage and reconciliation for missing events.'),
('005','Separate raw provider evidence, provider transcript, and canonical transcript','Accepted','Provider records and corrected business records have different evidential roles.','Preserve raw events immutably; normalize the provider transcript; create versioned canonical transcript and corrections with provenance.','Prevents silent rewriting and enables QA. Increases storage and model complexity.'),
('006','Use Temporal for durable asynchronous workflows','Accepted','Publication, tests, post-call processing, messaging, reports, retention, and reconciliation require durable retries and visibility.','Use Temporal workflows with task queues by domain. Keep authoritative business state in PostgreSQL.','Improves recovery and observability. Requires workflow versioning and careful PII minimization in histories.'),
('007','Use PostgreSQL as the authoritative application store','Accepted','The platform needs transactional versions, approvals, mappings, calls, audit, and aggregates.','Use PostgreSQL with Drizzle and explicit SQL for high-volume reporting; object storage for large assets.','Strong consistency and portability. Requires partitioning, archival, indexing, and zero-downtime migration discipline.'),
('008','Enforce tests and release gates server-side','Accepted','UI-only gates can be bypassed and provider behaviour is non-deterministic.','Release transitions are code-owned and require critical tests, approvals, dependency validity, and provider verification.','Improves trust and compliance. Adds release workflow complexity and human approval effort.'),
('009','Expose only code-owned typed business tools','Accepted','A voice agent must not invoke arbitrary actions or URLs.','Tools use a registry, JSON schemas, purpose, verification level, field allowlists, explicit result states, idempotency, and audit.','Prevents tool hallucination and false completion. Every new tool requires engineering and security review.'),
('010','Use a human-reviewed improvement loop','Accepted','Call trends are valuable but contain errors, anecdotes, and untrusted speech.','Calls create gaps and recommendations; humans draft, approve, test, and publish changes. No automatic production learning.','Reduces poisoning and accidental policy drift. Improvement is slower but controlled and measurable.'),
('011','Isolate provider integration behind an adapter and reconciliation service','Accepted','Provider APIs, fields, deprecations, and account capabilities may change.','Map provider DTOs at a boundary, return domain result unions, maintain a capability registry, and reconcile remote state.','Reduces vendor leakage and supports simulation. Does not promise easy provider replacement of live runtime.'),
('012','Use OIDC, backend RBAC, purpose checks, and protected audit','Accepted','The platform holds transcripts, customer context, sensitive cases, and powerful release controls.','Use OIDC/MFA support, server RBAC, purpose-based access, field masking, separation of duties, and immutable/protected audit events.','Supports least privilege and investigation. Requires role design, access reviews, and audited exports.'),
('013','Use AWS ECS Fargate as the reference production deployment','Proposed baseline','The build needs a secure, managed, EU-capable reference deployment without Kubernetes operational overhead.','Use Terraform for WAF/ALB, ECS services, RDS, Redis, S3/KMS, Secrets Manager, IAM, telemetry, backups, and budgets.','Portable application contracts remain. Region and managed-service choices must be verified during implementation.'),
('014','Make provider privacy, retention, ZRM, and residency explicit gates','Accepted','ElevenLabs receives live audio and provider settings vary by account and contract.','Record approved provider data posture and fail readiness when retention, redaction, residency, ZRM, DPA, or webhook dependencies are unresolved.','Avoids false local-only claims. May require enterprise features and commercial/legal onboarding.'),
('015','Exclude payment processing and restrict sensitive cases','Accepted','Voice calls may contain card or sensitive information, but the system is not a payment, medical, legal, or insurance decision platform.','Never request card data; interrupt and redirect; post-call redact; restrict sensitive cases; suppress offers; route to approved human queues.','Reduces risk but cannot prevent provider from hearing unsolicited live audio. Provider controls and incident processes remain essential.'),
]
for num,title,status,context,decision,consequence in adrs:
    text=f'''# ADR-{num}: {title}\n\n**Status:** {status}  \n**Date:** 2026-07-22  \n**Decision owners:** Quantum Parks product, architecture, security, and operations\n\n## Context\n\n{context}\n\n## Decision\n\n{decision}\n\n## Consequences\n\n{consequence}\n\n## Guardrails\n\n- Implementation must remain traceable to PRD v2.0.\n- Provider capability claims must be verified against current official documentation.\n- Security, privacy, payment exclusion, and sensitive-case requirements take precedence.\n- Material deviation requires a superseding ADR and updated compliance matrix.\n'''
    (OUT/f'ADR-{num}-{title.lower().replace(" ","-").replace("/","-")}.md').write_text(text,encoding='utf-8')
print('ADRs built')
